ALTER TABLE building MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE building MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE controller MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE controller MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE device MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE device MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE device_frequency MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE device_frequency MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE unit MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE unit MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE user MODIFY COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE user MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;
UPDATE `user` SET last_access = updated_at;
ALTER TABLE user MODIFY COLUMN last_access DATETIME NOT NULL;

ALTER TABLE token MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;
ALTER TABLE token MODIFY COLUMN expires DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;