package zesp03;

import javax.xml.crypto.Data;
import java.io.IOException;
import java.sql.*;
import java.time.Instant;
import java.util.List;

public class Start {
    public static void main(String[] args) throws IOException, SNMPException, SQLException, AdminException, InterruptedException {
        examine();
    }

    public static void examine() throws IOException, SQLException, SNMPException {
        Management m = new Management();
        System.out.println("start");
        long t0 = System.currentTimeMillis();

        m.examineAll();

        long t1 = System.currentTimeMillis();
        System.out.println("czas trwania " + (t1-t0) + "ms");
    }

    public static void fxd() throws SQLException {
        int[] src = {0x1f880};
        String z = new String(src, 0, 1);
        System.out.println("z = " + z);
        String sql = "INSERT INTO xd (z) VALUES (?)";
        try( Connection con = Database.connect();
            PreparedStatement prep = con.prepareStatement(sql) ) {
            prep.setString(1, z);
            prep.executeUpdate();
        }
        System.out.println("gotowe");
    }

    public static void f1() throws SQLException {
        try(Connection c = Database.connect();
            Statement st = c.createStatement() ) {
            String sql = "INSERT INTO controller (name, ipv4) VALUES (\"f2\", \"2.1.1.1\")";
            String[] arr = {"id"};
            int eu = st.executeUpdate(sql, arr);
            int uc = st.getUpdateCount();
            System.out.println("executeUpdate returned " + eu);
            System.out.println("getUpdateCount returned " + uc);
            ResultSet res = st.getGeneratedKeys();
            while(res.next()) {
                int colId = res.getInt("id");
                System.out.println("autoGeneratedKeys id = " + colId);
                int colXxx = res.getInt("xxx");
                System.out.println("autoGeneratedKeys xxx = " + colXxx);
            }
            res.close();
        }
    }

    public static void f5() throws SQLException {
        String sql = "INSERT INTO controller (name, ipv4) VALUES (?, ?)";
        try(Connection con = Database.connect();
            PreparedStatement prep = con.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS) ) {
            prep.setString(1, "f5");
            prep.setString(2, "5.1.1.1");
            int eu = prep.executeUpdate();
            System.out.println("eu=" + eu);
            int uc = prep.getUpdateCount();
            System.out.println("uc=" + uc);
            ResultSet res = prep.getGeneratedKeys();
            while(res.next()) {
                System.out.println("generated " + res.getInt(1) );
            }
            res.close();
        }
    }

}
